# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='driver',
            field=models.FileField(blank=True, null=True, upload_to='products/driver/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/img/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manual',
            field=models.FileField(blank=True, null=True, upload_to='products/manual/'),
        ),
    ]
