# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180816_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/img/'),
        ),
    ]
