# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180829_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shiping_total',
            new_name='shipping_total',
        ),
    ]
